// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DecisionResponse422Error_message
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Front image missing. Make sure the front image is available.")]
        #pragma warning disable CS1591
        FrontImageMissingMakeSureTheFrontImageIsAvailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "Back image missing. Make sure the back image is available.")]
        #pragma warning disable CS1591
        BackImageMissingMakeSureTheBackImageIsAvailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "Face image missing. Make sure the selfie image is available.")]
        #pragma warning disable CS1591
        FaceImageMissingMakeSureTheSelfieImageIsAvailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "Document not fully in frame.")]
        #pragma warning disable CS1591
        DocumentNotFullyInFrame,
        #pragma warning restore CS1591
        [EnumMember(Value = "Face not fully in frame.")]
        #pragma warning disable CS1591
        FaceNotFullyInFrame,
        #pragma warning restore CS1591
    }
}
