// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DecisionResponseStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ACCEPTED")]
        #pragma warning disable CS1591
        Accepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "REVIEW")]
        #pragma warning disable CS1591
        Review,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECLINED")]
        #pragma warning disable CS1591
        Declined,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "NO_RESULT")]
        #pragma warning disable CS1591
        NoResult,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_RESULT")]
        #pragma warning disable CS1591
        PendingResult,
        #pragma warning restore CS1591
    }
}
