// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    /// <summary>Type of the identification document provided.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Document_documentType
    {
        [EnumMember(Value = "PASSPORT")]
        #pragma warning disable CS1591
        PASSPORT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DRIVERS_LICENSE")]
        #pragma warning disable CS1591
        DRIVERS_LICENSE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ID_CARD")]
        #pragma warning disable CS1591
        ID_CARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESIDENCE_PERMIT")]
        #pragma warning disable CS1591
        RESIDENCE_PERMIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "MILITARY_ID")]
        #pragma warning disable CS1591
        MILITARY_ID,
        #pragma warning restore CS1591
        [EnumMember(Value = "VISA")]
        #pragma warning disable CS1591
        VISA,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEALTH_CARD")]
        #pragma warning disable CS1591
        HEALTH_CARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAVEL_DOCUMENT")]
        #pragma warning disable CS1591
        TRAVEL_DOCUMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "VOTER_ID")]
        #pragma warning disable CS1591
        VOTER_ID,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAX_ID")]
        #pragma warning disable CS1591
        TAX_ID,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        OTHER,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        UNKNOWN,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNSUPPORTED")]
        #pragma warning disable CS1591
        UNSUPPORTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_STARTED")]
        #pragma warning disable CS1591
        NOT_STARTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        ERROR,
        #pragma warning restore CS1591
    }
}
