// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    /// <summary>Type of the identification document provided.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DocumentDocumentType
    {
        [EnumMember(Value = "PASSPORT")]
        #pragma warning disable CS1591
        Passport,
        #pragma warning restore CS1591
        [EnumMember(Value = "DRIVERS_LICENSE")]
        #pragma warning disable CS1591
        DriversLicense,
        #pragma warning restore CS1591
        [EnumMember(Value = "ID_CARD")]
        #pragma warning disable CS1591
        IdCard,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESIDENCE_PERMIT")]
        #pragma warning disable CS1591
        ResidencePermit,
        #pragma warning restore CS1591
        [EnumMember(Value = "MILITARY_ID")]
        #pragma warning disable CS1591
        MilitaryId,
        #pragma warning restore CS1591
        [EnumMember(Value = "VISA")]
        #pragma warning disable CS1591
        Visa,
        #pragma warning restore CS1591
        [EnumMember(Value = "HEALTH_CARD")]
        #pragma warning disable CS1591
        HealthCard,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRAVEL_DOCUMENT")]
        #pragma warning disable CS1591
        TravelDocument,
        #pragma warning restore CS1591
        [EnumMember(Value = "VOTER_ID")]
        #pragma warning disable CS1591
        VoterId,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAX_ID")]
        #pragma warning disable CS1591
        TaxId,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTHER")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNSUPPORTED")]
        #pragma warning disable CS1591
        Unsupported,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_STARTED")]
        #pragma warning disable CS1591
        NotStarted,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
