// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Document : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Document number that is non-iso latin</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternateDocumentNumber { get; set; }
#nullable restore
#else
        public string AlternateDocumentNumber { get; set; }
#endif
        /// <summary>Document number that is non-iso latin</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternateDocumentNumber2 { get; set; }
#nullable restore
#else
        public string AlternateDocumentNumber2 { get; set; }
#endif
        /// <summary>Document number that is non-iso latin</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternateDocumentNumber3 { get; set; }
#nullable restore
#else
        public string AlternateDocumentNumber3 { get; set; }
#endif
        /// <summary>Document number that is non-iso latin</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternateDocumentNumber4 { get; set; }
#nullable restore
#else
        public string AlternateDocumentNumber4 { get; set; }
#endif
        /// <summary>Expiry date that is non-iso latin</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternateExpiryDate { get; set; }
#nullable restore
#else
        public string AlternateExpiryDate { get; set; }
#endif
        /// <summary>Issue date that is non-iso latin</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternateIssueDate { get; set; }
#nullable restore
#else
        public string AlternateIssueDate { get; set; }
#endif
        /// <summary>The driving license category if the submitted document is of type DRIVERS_LICENSE</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DlCategory { get; set; }
#nullable restore
#else
        public string DlCategory { get; set; }
#endif
        /// <summary>The ISO alpha-2 code of issuing country of the document.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentCountry { get; set; }
#nullable restore
#else
        public string DocumentCountry { get; set; }
#endif
        /// <summary>The documentName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentName { get; set; }
#nullable restore
#else
        public string DocumentName { get; set; }
#endif
        /// <summary>The primary document identifier apparent in all documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentNumber { get; set; }
#nullable restore
#else
        public string DocumentNumber { get; set; }
#endif
        /// <summary>The second document identifier that is apparent in some documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentNumber2 { get; set; }
#nullable restore
#else
        public string DocumentNumber2 { get; set; }
#endif
        /// <summary>The third document identifier that is apparent in some documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentNumber3 { get; set; }
#nullable restore
#else
        public string DocumentNumber3 { get; set; }
#endif
        /// <summary>The fourth document identifier that is apparent in some documents.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentNumber4 { get; set; }
#nullable restore
#else
        public string DocumentNumber4 { get; set; }
#endif
        /// <summary>Type of the identification document provided.</summary>
        public global::Soenneker.Trulioo.OpenApiClient.Models.Document_documentType? DocumentType { get; set; }
        /// <summary>Date at which document will or has expired.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpirationDate { get; set; }
#nullable restore
#else
        public string ExpirationDate { get; set; }
#endif
        /// <summary>Date at which document is issued by a governing body.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IssueDate { get; set; }
#nullable restore
#else
        public string IssueDate { get; set; }
#endif
        /// <summary>The code of issuing jurisdiction of the document.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JurisdictionCode { get; set; }
#nullable restore
#else
        public string JurisdictionCode { get; set; }
#endif
        /// <summary>The first mrz line in passport or id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MrzLineOne { get; set; }
#nullable restore
#else
        public string MrzLineOne { get; set; }
#endif
        /// <summary>The third mrz line in passport or id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MrzLineThree { get; set; }
#nullable restore
#else
        public string MrzLineThree { get; set; }
#endif
        /// <summary>The second mrz line in passport or id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MrzLineTwo { get; set; }
#nullable restore
#else
        public string MrzLineTwo { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.Document"/> and sets the default values.
        /// </summary>
        public Document()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.Document"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Trulioo.OpenApiClient.Models.Document CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Trulioo.OpenApiClient.Models.Document();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alternateDocumentNumber", n => { AlternateDocumentNumber = n.GetStringValue(); } },
                { "alternateDocumentNumber2", n => { AlternateDocumentNumber2 = n.GetStringValue(); } },
                { "alternateDocumentNumber3", n => { AlternateDocumentNumber3 = n.GetStringValue(); } },
                { "alternateDocumentNumber4", n => { AlternateDocumentNumber4 = n.GetStringValue(); } },
                { "alternateExpiryDate", n => { AlternateExpiryDate = n.GetStringValue(); } },
                { "alternateIssueDate", n => { AlternateIssueDate = n.GetStringValue(); } },
                { "dlCategory", n => { DlCategory = n.GetStringValue(); } },
                { "documentCountry", n => { DocumentCountry = n.GetStringValue(); } },
                { "documentName", n => { DocumentName = n.GetStringValue(); } },
                { "documentNumber", n => { DocumentNumber = n.GetStringValue(); } },
                { "documentNumber2", n => { DocumentNumber2 = n.GetStringValue(); } },
                { "documentNumber3", n => { DocumentNumber3 = n.GetStringValue(); } },
                { "documentNumber4", n => { DocumentNumber4 = n.GetStringValue(); } },
                { "documentType", n => { DocumentType = n.GetEnumValue<global::Soenneker.Trulioo.OpenApiClient.Models.Document_documentType>(); } },
                { "expirationDate", n => { ExpirationDate = n.GetStringValue(); } },
                { "issueDate", n => { IssueDate = n.GetStringValue(); } },
                { "jurisdictionCode", n => { JurisdictionCode = n.GetStringValue(); } },
                { "mrzLineOne", n => { MrzLineOne = n.GetStringValue(); } },
                { "mrzLineThree", n => { MrzLineThree = n.GetStringValue(); } },
                { "mrzLineTwo", n => { MrzLineTwo = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("alternateDocumentNumber", AlternateDocumentNumber);
            writer.WriteStringValue("alternateDocumentNumber2", AlternateDocumentNumber2);
            writer.WriteStringValue("alternateDocumentNumber3", AlternateDocumentNumber3);
            writer.WriteStringValue("alternateDocumentNumber4", AlternateDocumentNumber4);
            writer.WriteStringValue("alternateExpiryDate", AlternateExpiryDate);
            writer.WriteStringValue("alternateIssueDate", AlternateIssueDate);
            writer.WriteStringValue("dlCategory", DlCategory);
            writer.WriteStringValue("documentCountry", DocumentCountry);
            writer.WriteStringValue("documentName", DocumentName);
            writer.WriteStringValue("documentNumber", DocumentNumber);
            writer.WriteStringValue("documentNumber2", DocumentNumber2);
            writer.WriteStringValue("documentNumber3", DocumentNumber3);
            writer.WriteStringValue("documentNumber4", DocumentNumber4);
            writer.WriteEnumValue<global::Soenneker.Trulioo.OpenApiClient.Models.Document_documentType>("documentType", DocumentType);
            writer.WriteStringValue("expirationDate", ExpirationDate);
            writer.WriteStringValue("issueDate", IssueDate);
            writer.WriteStringValue("jurisdictionCode", JurisdictionCode);
            writer.WriteStringValue("mrzLineOne", MrzLineOne);
            writer.WriteStringValue("mrzLineThree", MrzLineThree);
            writer.WriteStringValue("mrzLineTwo", MrzLineTwo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
