// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    /// <summary>
    /// The object contain all submitted images.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImageIds : IAdditionalDataHolder, IParsable
    {
        /// <summary>The short lived access token in the format of JWT which contains ID of images. This access token is used as authorization token to retrieve images.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccessToken { get; set; }
#nullable restore
#else
        public string AccessToken { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The backDocumentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackDocumentId { get; set; }
#nullable restore
#else
        public string BackDocumentId { get; set; }
#endif
        /// <summary>URL to download document back image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentBackUrl { get; set; }
#nullable restore
#else
        public string DocumentBackUrl { get; set; }
#endif
        /// <summary>URL to download document front image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentFrontUrl { get; set; }
#nullable restore
#else
        public string DocumentFrontUrl { get; set; }
#endif
        /// <summary>The frontDocumentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FrontDocumentId { get; set; }
#nullable restore
#else
        public string FrontDocumentId { get; set; }
#endif
        /// <summary>The selfieId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SelfieId { get; set; }
#nullable restore
#else
        public string SelfieId { get; set; }
#endif
        /// <summary>URL to download selfie image.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SelfieUrl { get; set; }
#nullable restore
#else
        public string SelfieUrl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.ImageIds"/> and sets the default values.
        /// </summary>
        public ImageIds()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.ImageIds"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Trulioo.OpenApiClient.Models.ImageIds CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Trulioo.OpenApiClient.Models.ImageIds();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessToken", n => { AccessToken = n.GetStringValue(); } },
                { "backDocumentId", n => { BackDocumentId = n.GetStringValue(); } },
                { "documentBackUrl", n => { DocumentBackUrl = n.GetStringValue(); } },
                { "documentFrontUrl", n => { DocumentFrontUrl = n.GetStringValue(); } },
                { "frontDocumentId", n => { FrontDocumentId = n.GetStringValue(); } },
                { "selfieId", n => { SelfieId = n.GetStringValue(); } },
                { "selfieUrl", n => { SelfieUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accessToken", AccessToken);
            writer.WriteStringValue("backDocumentId", BackDocumentId);
            writer.WriteStringValue("documentBackUrl", DocumentBackUrl);
            writer.WriteStringValue("documentFrontUrl", DocumentFrontUrl);
            writer.WriteStringValue("frontDocumentId", FrontDocumentId);
            writer.WriteStringValue("selfieId", SelfieId);
            writer.WriteStringValue("selfieUrl", SelfieUrl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
