// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Indicator_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DOCUMENT")]
        #pragma warning disable CS1591
        DOCUMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "FACE_MATCH")]
        #pragma warning disable CS1591
        FACE_MATCH,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIVENESS")]
        #pragma warning disable CS1591
        LIVENESS,
        #pragma warning restore CS1591
    }
}
