// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Indicator : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The result property</summary>
        public global::Soenneker.Trulioo.OpenApiClient.Models.Indicator_result? Result { get; set; }
        /// <summary>The score property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Score { get; set; }
#nullable restore
#else
        public string Score { get; set; }
#endif
        /// <summary>The subindicators property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.Subindicator>? Subindicators { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.Subindicator> Subindicators { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Trulioo.OpenApiClient.Models.Indicator_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.Indicator"/> and sets the default values.
        /// </summary>
        public Indicator()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.Indicator"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Trulioo.OpenApiClient.Models.Indicator CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Trulioo.OpenApiClient.Models.Indicator();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "result", n => { Result = n.GetEnumValue<global::Soenneker.Trulioo.OpenApiClient.Models.Indicator_result>(); } },
                { "score", n => { Score = n.GetStringValue(); } },
                { "subindicators", n => { Subindicators = n.GetCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.Subindicator>(global::Soenneker.Trulioo.OpenApiClient.Models.Subindicator.CreateFromDiscriminatorValue)?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Trulioo.OpenApiClient.Models.Indicator_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteEnumValue<global::Soenneker.Trulioo.OpenApiClient.Models.Indicator_result>("result", Result);
            writer.WriteStringValue("score", Score);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.Subindicator>("subindicators", Subindicators);
            writer.WriteEnumValue<global::Soenneker.Trulioo.OpenApiClient.Models.Indicator_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
