// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum LivenessCheck_calibration
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "MEDIUM")]
        #pragma warning disable CS1591
        MEDIUM,
        #pragma warning restore CS1591
        [EnumMember(Value = "HIGH")]
        #pragma warning disable CS1591
        HIGH,
        #pragma warning restore CS1591
    }
}
