// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MatcherToken_precision
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NO_MATCH")]
        #pragma warning disable CS1591
        NO_MATCH,
        #pragma warning restore CS1591
        [EnumMember(Value = "POOR_MATCH")]
        #pragma warning disable CS1591
        POOR_MATCH,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTIAL_MATCH")]
        #pragma warning disable CS1591
        PARTIAL_MATCH,
        #pragma warning restore CS1591
        [EnumMember(Value = "HIGH_PARTIAL_MATCH")]
        #pragma warning disable CS1591
        HIGH_PARTIAL_MATCH,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXACT_MATCH")]
        #pragma warning disable CS1591
        EXACT_MATCH,
        #pragma warning restore CS1591
    }
}
