// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MatcherTokenPrecision
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NO_MATCH")]
        #pragma warning disable CS1591
        NoMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "POOR_MATCH")]
        #pragma warning disable CS1591
        PoorMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTIAL_MATCH")]
        #pragma warning disable CS1591
        PartialMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "HIGH_PARTIAL_MATCH")]
        #pragma warning disable CS1591
        HighPartialMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXACT_MATCH")]
        #pragma warning disable CS1591
        ExactMatch,
        #pragma warning restore CS1591
    }
}
