// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Person : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alternateDateOfBirth property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternateDateOfBirth { get; set; }
#nullable restore
#else
        public string AlternateDateOfBirth { get; set; }
#endif
        /// <summary>The alternateFirstLastname property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternateFirstLastname { get; set; }
#nullable restore
#else
        public string AlternateFirstLastname { get; set; }
#endif
        /// <summary>First name that is non-iso latin</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternateFirstName { get; set; }
#nullable restore
#else
        public string AlternateFirstName { get; set; }
#endif
        /// <summary>Full name that is non-iso latin</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternateFullName { get; set; }
#nullable restore
#else
        public string AlternateFullName { get; set; }
#endif
        /// <summary>Middle name that is non-iso latin</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternateLastName { get; set; }
#nullable restore
#else
        public string AlternateLastName { get; set; }
#endif
        /// <summary>The alternateLocation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.Person_alternateLocation? AlternateLocation { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.Person_alternateLocation AlternateLocation { get; set; }
#endif
        /// <summary>Middle name that is non-iso latin</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternateMiddleName { get; set; }
#nullable restore
#else
        public string AlternateMiddleName { get; set; }
#endif
        /// <summary>The alternateSecondLastname property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AlternateSecondLastname { get; set; }
#nullable restore
#else
        public string AlternateSecondLastname { get; set; }
#endif
        /// <summary>Last name by birth</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BirthLastName { get; set; }
#nullable restore
#else
        public string BirthLastName { get; set; }
#endif
        /// <summary>Date of birth of the subject/applicant (ISO 8601)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateOfBirth { get; set; }
#nullable restore
#else
        public string DateOfBirth { get; set; }
#endif
        /// <summary>The firstLastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstLastName { get; set; }
#nullable restore
#else
        public string FirstLastName { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>Full name of the subject/applicant. Used in case of indistinguishable first and last name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FullName { get; set; }
#nullable restore
#else
        public string FullName { get; set; }
#endif
        /// <summary>Person&apos;s gender as denoted by the letters M for male or F for female.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Gender { get; set; }
#nullable restore
#else
        public string Gender { get; set; }
#endif
        /// <summary>The lastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.Address? Location { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.Address Location { get; set; }
#endif
        /// <summary>The middleName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MiddleName { get; set; }
#nullable restore
#else
        public string MiddleName { get; set; }
#endif
        /// <summary>A person&apos;s nationality.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Nationality { get; set; }
#nullable restore
#else
        public string Nationality { get; set; }
#endif
        /// <summary>Place of birth of the subject/applicant</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PlaceOfBirth { get; set; }
#nullable restore
#else
        public string PlaceOfBirth { get; set; }
#endif
        /// <summary>The secondLastname property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecondLastname { get; set; }
#nullable restore
#else
        public string SecondLastname { get; set; }
#endif
        /// <summary>Last name of spouse</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SpouseLastName { get; set; }
#nullable restore
#else
        public string SpouseLastName { get; set; }
#endif
        /// <summary>The standardizedLocation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.Address? StandardizedLocation { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.Address StandardizedLocation { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.Person"/> and sets the default values.
        /// </summary>
        public Person()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.Person"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Trulioo.OpenApiClient.Models.Person CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Trulioo.OpenApiClient.Models.Person();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alternateDateOfBirth", n => { AlternateDateOfBirth = n.GetStringValue(); } },
                { "alternateFirstLastname", n => { AlternateFirstLastname = n.GetStringValue(); } },
                { "alternateFirstName", n => { AlternateFirstName = n.GetStringValue(); } },
                { "alternateFullName", n => { AlternateFullName = n.GetStringValue(); } },
                { "alternateLastName", n => { AlternateLastName = n.GetStringValue(); } },
                { "alternateLocation", n => { AlternateLocation = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.Person_alternateLocation>(global::Soenneker.Trulioo.OpenApiClient.Models.Person_alternateLocation.CreateFromDiscriminatorValue); } },
                { "alternateMiddleName", n => { AlternateMiddleName = n.GetStringValue(); } },
                { "alternateSecondLastname", n => { AlternateSecondLastname = n.GetStringValue(); } },
                { "birthLastName", n => { BirthLastName = n.GetStringValue(); } },
                { "dateOfBirth", n => { DateOfBirth = n.GetStringValue(); } },
                { "firstLastName", n => { FirstLastName = n.GetStringValue(); } },
                { "firstName", n => { FirstName = n.GetStringValue(); } },
                { "fullName", n => { FullName = n.GetStringValue(); } },
                { "gender", n => { Gender = n.GetStringValue(); } },
                { "lastName", n => { LastName = n.GetStringValue(); } },
                { "location", n => { Location = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.Address>(global::Soenneker.Trulioo.OpenApiClient.Models.Address.CreateFromDiscriminatorValue); } },
                { "middleName", n => { MiddleName = n.GetStringValue(); } },
                { "nationality", n => { Nationality = n.GetStringValue(); } },
                { "placeOfBirth", n => { PlaceOfBirth = n.GetStringValue(); } },
                { "secondLastname", n => { SecondLastname = n.GetStringValue(); } },
                { "spouseLastName", n => { SpouseLastName = n.GetStringValue(); } },
                { "standardizedLocation", n => { StandardizedLocation = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.Address>(global::Soenneker.Trulioo.OpenApiClient.Models.Address.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("alternateDateOfBirth", AlternateDateOfBirth);
            writer.WriteStringValue("alternateFirstLastname", AlternateFirstLastname);
            writer.WriteStringValue("alternateFirstName", AlternateFirstName);
            writer.WriteStringValue("alternateFullName", AlternateFullName);
            writer.WriteStringValue("alternateLastName", AlternateLastName);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.Person_alternateLocation>("alternateLocation", AlternateLocation);
            writer.WriteStringValue("alternateMiddleName", AlternateMiddleName);
            writer.WriteStringValue("alternateSecondLastname", AlternateSecondLastname);
            writer.WriteStringValue("birthLastName", BirthLastName);
            writer.WriteStringValue("dateOfBirth", DateOfBirth);
            writer.WriteStringValue("firstLastName", FirstLastName);
            writer.WriteStringValue("firstName", FirstName);
            writer.WriteStringValue("fullName", FullName);
            writer.WriteStringValue("gender", Gender);
            writer.WriteStringValue("lastName", LastName);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.Address>("location", Location);
            writer.WriteStringValue("middleName", MiddleName);
            writer.WriteStringValue("nationality", Nationality);
            writer.WriteStringValue("placeOfBirth", PlaceOfBirth);
            writer.WriteStringValue("secondLastname", SecondLastname);
            writer.WriteStringValue("spouseLastName", SpouseLastName);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.Address>("standardizedLocation", StandardizedLocation);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
