// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SubindicatorCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "DAMAGED")]
        #pragma warning disable CS1591
        Damaged,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNSUPPORTED_DOCUMENT")]
        #pragma warning disable CS1591
        UnsupportedDocument,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CHARACTERS")]
        #pragma warning disable CS1591
        InvalidCharacters,
        #pragma warning restore CS1591
        [EnumMember(Value = "POOR_IMAGE_QUALITY")]
        #pragma warning disable CS1591
        PoorImageQuality,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUSPICIOUS")]
        #pragma warning disable CS1591
        Suspicious,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCREEN_USED")]
        #pragma warning disable CS1591
        ScreenUsed,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRINTOUT_USED")]
        #pragma warning disable CS1591
        PrintoutUsed,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_XCHECK_REFERENCE")]
        #pragma warning disable CS1591
        DataXcheckReference,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOCUMENT_TAMPERING")]
        #pragma warning disable CS1591
        DocumentTampering,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIVENESS_FAIL")]
        #pragma warning disable CS1591
        LivenessFail,
        #pragma warning restore CS1591
        [EnumMember(Value = "PHOTOS_MISSING")]
        #pragma warning disable CS1591
        PhotosMissing,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECLINED_FACE_MATCH")]
        #pragma warning disable CS1591
        DeclinedFaceMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCEPTED_DOCUMENT")]
        #pragma warning disable CS1591
        AcceptedDocument,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCEPTED_FACE_MATCH")]
        #pragma warning disable CS1591
        AcceptedFaceMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCEPTED_LIVENESS")]
        #pragma warning disable CS1591
        AcceptedLiveness,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR_DOCUMENT")]
        #pragma warning disable CS1591
        ErrorDocument,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR_FACE_MATCH")]
        #pragma warning disable CS1591
        ErrorFaceMatch,
        #pragma warning restore CS1591
        [EnumMember(Value = "MISSING_FIELD")]
        #pragma warning disable CS1591
        MissingField,
        #pragma warning restore CS1591
        [EnumMember(Value = "ISSUE_DATE_OVER_10Y")]
        #pragma warning disable CS1591
        IssueDateOver10Y,
        #pragma warning restore CS1591
        [EnumMember(Value = "DIFFERENT_DOCUMENTS")]
        #pragma warning disable CS1591
        DifferentDocuments,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_MRZ")]
        #pragma warning disable CS1591
        InvalidMrz,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_BARCODE")]
        #pragma warning disable CS1591
        InvalidBarcode,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_XCHECK_REFERENCE_DOB")]
        #pragma warning disable CS1591
        DataXcheckReferenceDob,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_XCHECK_REFERENCE_GIVEN_NAME")]
        #pragma warning disable CS1591
        DataXcheckReferenceGivenName,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_XCHECK_REFERENCE_SURNAME")]
        #pragma warning disable CS1591
        DataXcheckReferenceSurname,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_XCHECK_REFERENCE_NAME")]
        #pragma warning disable CS1591
        DataXcheckReferenceName,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_XCHECK_REFERENCE_ADDRESS")]
        #pragma warning disable CS1591
        DataXcheckReferenceAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_XCHECK_REFERENCE_EXPIRY")]
        #pragma warning disable CS1591
        DataXcheckReferenceExpiry,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CONFIG_DOCTYPE")]
        #pragma warning disable CS1591
        InvalidConfigDoctype,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CONFIG_COUNTRY")]
        #pragma warning disable CS1591
        InvalidConfigCountry,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN_DOCUMENT_TYPE")]
        #pragma warning disable CS1591
        UnknownDocumentType,
        #pragma warning restore CS1591
        [EnumMember(Value = "MISSING_CODE_MAPPING")]
        #pragma warning disable CS1591
        MissingCodeMapping,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CONFIG_JURISDICTION")]
        #pragma warning disable CS1591
        InvalidConfigJurisdiction,
        #pragma warning restore CS1591
        [EnumMember(Value = "JURISDICTION_NOT_FOUND")]
        #pragma warning disable CS1591
        JurisdictionNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOCUMENT_NOT_FOUND")]
        #pragma warning disable CS1591
        DocumentNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOCUMENT_PHOTO_NOT_FOUND")]
        #pragma warning disable CS1591
        DocumentPhotoNotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR_DOCUMENT_LIVENESS")]
        #pragma warning disable CS1591
        ErrorDocumentLiveness,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOCUMENT_CROPPED")]
        #pragma warning disable CS1591
        DocumentCropped,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOO_MANY_DOCUMENTS")]
        #pragma warning disable CS1591
        TooManyDocuments,
        #pragma warning restore CS1591
        [EnumMember(Value = "INPUT_MATCH_FAILED")]
        #pragma warning disable CS1591
        InputMatchFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "INPUT_MATCH_PASSED")]
        #pragma warning disable CS1591
        InputMatchPassed,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOMER_INPUT_MISSING")]
        #pragma warning disable CS1591
        CustomerInputMissing,
        #pragma warning restore CS1591
        [EnumMember(Value = "OCR_MISSING")]
        #pragma warning disable CS1591
        OcrMissing,
        #pragma warning restore CS1591
    }
}
