// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Subindicator_code
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "NONE")]
        #pragma warning disable CS1591
        NONE,
        #pragma warning restore CS1591
        [EnumMember(Value = "DAMAGED")]
        #pragma warning disable CS1591
        DAMAGED,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNSUPPORTED_DOCUMENT")]
        #pragma warning disable CS1591
        UNSUPPORTED_DOCUMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED")]
        #pragma warning disable CS1591
        EXPIRED,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CHARACTERS")]
        #pragma warning disable CS1591
        INVALID_CHARACTERS,
        #pragma warning restore CS1591
        [EnumMember(Value = "POOR_IMAGE_QUALITY")]
        #pragma warning disable CS1591
        POOR_IMAGE_QUALITY,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUSPICIOUS")]
        #pragma warning disable CS1591
        SUSPICIOUS,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCREEN_USED")]
        #pragma warning disable CS1591
        SCREEN_USED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRINTOUT_USED")]
        #pragma warning disable CS1591
        PRINTOUT_USED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_XCHECK_REFERENCE")]
        #pragma warning disable CS1591
        DATA_XCHECK_REFERENCE,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOCUMENT_TAMPERING")]
        #pragma warning disable CS1591
        DOCUMENT_TAMPERING,
        #pragma warning restore CS1591
        [EnumMember(Value = "LIVENESS_FAIL")]
        #pragma warning disable CS1591
        LIVENESS_FAIL,
        #pragma warning restore CS1591
        [EnumMember(Value = "PHOTOS_MISSING")]
        #pragma warning disable CS1591
        PHOTOS_MISSING,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECLINED_FACE_MATCH")]
        #pragma warning disable CS1591
        DECLINED_FACE_MATCH,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCEPTED_DOCUMENT")]
        #pragma warning disable CS1591
        ACCEPTED_DOCUMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCEPTED_FACE_MATCH")]
        #pragma warning disable CS1591
        ACCEPTED_FACE_MATCH,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCEPTED_LIVENESS")]
        #pragma warning disable CS1591
        ACCEPTED_LIVENESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR_DOCUMENT")]
        #pragma warning disable CS1591
        ERROR_DOCUMENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR_FACE_MATCH")]
        #pragma warning disable CS1591
        ERROR_FACE_MATCH,
        #pragma warning restore CS1591
        [EnumMember(Value = "MISSING_FIELD")]
        #pragma warning disable CS1591
        MISSING_FIELD,
        #pragma warning restore CS1591
        [EnumMember(Value = "ISSUE_DATE_OVER_10Y")]
        #pragma warning disable CS1591
        ISSUE_DATE_OVER_10Y,
        #pragma warning restore CS1591
        [EnumMember(Value = "DIFFERENT_DOCUMENTS")]
        #pragma warning disable CS1591
        DIFFERENT_DOCUMENTS,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_MRZ")]
        #pragma warning disable CS1591
        INVALID_MRZ,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_BARCODE")]
        #pragma warning disable CS1591
        INVALID_BARCODE,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_XCHECK_REFERENCE_DOB")]
        #pragma warning disable CS1591
        DATA_XCHECK_REFERENCE_DOB,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_XCHECK_REFERENCE_GIVEN_NAME")]
        #pragma warning disable CS1591
        DATA_XCHECK_REFERENCE_GIVEN_NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_XCHECK_REFERENCE_SURNAME")]
        #pragma warning disable CS1591
        DATA_XCHECK_REFERENCE_SURNAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_XCHECK_REFERENCE_NAME")]
        #pragma warning disable CS1591
        DATA_XCHECK_REFERENCE_NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_XCHECK_REFERENCE_ADDRESS")]
        #pragma warning disable CS1591
        DATA_XCHECK_REFERENCE_ADDRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATA_XCHECK_REFERENCE_EXPIRY")]
        #pragma warning disable CS1591
        DATA_XCHECK_REFERENCE_EXPIRY,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CONFIG_DOCTYPE")]
        #pragma warning disable CS1591
        INVALID_CONFIG_DOCTYPE,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CONFIG_COUNTRY")]
        #pragma warning disable CS1591
        INVALID_CONFIG_COUNTRY,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNKNOWN_DOCUMENT_TYPE")]
        #pragma warning disable CS1591
        UNKNOWN_DOCUMENT_TYPE,
        #pragma warning restore CS1591
        [EnumMember(Value = "MISSING_CODE_MAPPING")]
        #pragma warning disable CS1591
        MISSING_CODE_MAPPING,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALID_CONFIG_JURISDICTION")]
        #pragma warning disable CS1591
        INVALID_CONFIG_JURISDICTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "JURISDICTION_NOT_FOUND")]
        #pragma warning disable CS1591
        JURISDICTION_NOT_FOUND,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOCUMENT_NOT_FOUND")]
        #pragma warning disable CS1591
        DOCUMENT_NOT_FOUND,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOCUMENT_PHOTO_NOT_FOUND")]
        #pragma warning disable CS1591
        DOCUMENT_PHOTO_NOT_FOUND,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR_DOCUMENT_LIVENESS")]
        #pragma warning disable CS1591
        ERROR_DOCUMENT_LIVENESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOCUMENT_CROPPED")]
        #pragma warning disable CS1591
        DOCUMENT_CROPPED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOO_MANY_DOCUMENTS")]
        #pragma warning disable CS1591
        TOO_MANY_DOCUMENTS,
        #pragma warning restore CS1591
        [EnumMember(Value = "INPUT_MATCH_FAILED")]
        #pragma warning disable CS1591
        INPUT_MATCH_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "INPUT_MATCH_PASSED")]
        #pragma warning disable CS1591
        INPUT_MATCH_PASSED,
        #pragma warning restore CS1591
        [EnumMember(Value = "CUSTOMER_INPUT_MISSING")]
        #pragma warning disable CS1591
        CUSTOMER_INPUT_MISSING,
        #pragma warning restore CS1591
        [EnumMember(Value = "OCR_MISSING")]
        #pragma warning disable CS1591
        OCR_MISSING,
        #pragma warning restore CS1591
    }
}
