// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TransactionConfiguration_matcherConfigs_matchers_token
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "FIRST_NAME")]
        #pragma warning disable CS1591
        FIRST_NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "MIDDLE_NAME")]
        #pragma warning disable CS1591
        MIDDLE_NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "LAST_NAME")]
        #pragma warning disable CS1591
        LAST_NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "FULL_NAME")]
        #pragma warning disable CS1591
        FULL_NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATE_OF_BIRTH")]
        #pragma warning disable CS1591
        DATE_OF_BIRTH,
        #pragma warning restore CS1591
        [EnumMember(Value = "ADDRESS_LINE_1")]
        #pragma warning disable CS1591
        ADDRESS_LINE_1,
        #pragma warning restore CS1591
        [EnumMember(Value = "CITY")]
        #pragma warning disable CS1591
        CITY,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATE_PROVINCE")]
        #pragma warning disable CS1591
        STATE_PROVINCE,
        #pragma warning restore CS1591
        [EnumMember(Value = "POSTAL_CODE")]
        #pragma warning disable CS1591
        POSTAL_CODE,
        #pragma warning restore CS1591
        [EnumMember(Value = "COUNTRY")]
        #pragma warning disable CS1591
        COUNTRY,
        #pragma warning restore CS1591
        [EnumMember(Value = "FIRST_LAST_NAME")]
        #pragma warning disable CS1591
        FIRST_LAST_NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "SECOND_LAST_NAME")]
        #pragma warning disable CS1591
        SECOND_LAST_NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPOUSE_LAST_NAME")]
        #pragma warning disable CS1591
        SPOUSE_LAST_NAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "BIRTH_LAST_NAME")]
        #pragma warning disable CS1591
        BIRTH_LAST_NAME,
        #pragma warning restore CS1591
    }
}
