// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransactionConfiguration : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Document liveness check configuration (NOTE: If set, this config overrides documentLivenessOptions). Supported Calibrations: Screen Used=[MEDIUM, HIGH], Printout=[MEDIUM, HIGH] Portrait Substitution=[MEDIUM, HIGH], Digital Manipulation=[LOW, MEDIUM, HIGH].</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentLivenessConfig? DocumentLivenessConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentLivenessConfig DocumentLivenessConfig { get; set; }
#endif
        /// <summary>Options about the submitted image</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentLivenessOptions? DocumentLivenessOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentLivenessOptions DocumentLivenessOptions { get; set; }
#endif
        /// <summary>Document verification configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification? DocumentVerification { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification DocumentVerification { get; set; }
#endif
        /// <summary>Configuration for selfie-only transactions that reuse a prior document verification. When provided, the transaction imports document images from a completed transaction owned by the same organization and performs face match plus selfie liveness using those images and the selfie captured in the following step.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_faceMatchVerification? FaceMatchVerification { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_faceMatchVerification FaceMatchVerification { get; set; }
#endif
        /// <summary>Matcher configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs>? MatcherConfigs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs> MatcherConfigs { get; set; }
#endif
        /// <summary>Selfie liveness verification configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_selfieVerification? SelfieVerification { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_selfieVerification SelfieVerification { get; set; }
#endif
        /// <summary>Customer Input Personal Identification Information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_subjectInfo? SubjectInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_subjectInfo SubjectInfo { get; set; }
#endif
        /// <summary>List of Customer Input Personal Identification Information</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_subjectInfoList>? SubjectInfoList { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_subjectInfoList> SubjectInfoList { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration"/> and sets the default values.
        /// </summary>
        public TransactionConfiguration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "documentLivenessConfig", n => { DocumentLivenessConfig = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentLivenessConfig>(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentLivenessConfig.CreateFromDiscriminatorValue); } },
                { "documentLivenessOptions", n => { DocumentLivenessOptions = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentLivenessOptions>(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentLivenessOptions.CreateFromDiscriminatorValue); } },
                { "documentVerification", n => { DocumentVerification = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification>(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification.CreateFromDiscriminatorValue); } },
                { "faceMatchVerification", n => { FaceMatchVerification = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_faceMatchVerification>(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_faceMatchVerification.CreateFromDiscriminatorValue); } },
                { "matcherConfigs", n => { MatcherConfigs = n.GetCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs>(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs.CreateFromDiscriminatorValue)?.AsList(); } },
                { "selfieVerification", n => { SelfieVerification = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_selfieVerification>(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_selfieVerification.CreateFromDiscriminatorValue); } },
                { "subjectInfo", n => { SubjectInfo = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_subjectInfo>(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_subjectInfo.CreateFromDiscriminatorValue); } },
                { "subjectInfoList", n => { SubjectInfoList = n.GetCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_subjectInfoList>(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_subjectInfoList.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentLivenessConfig>("documentLivenessConfig", DocumentLivenessConfig);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentLivenessOptions>("documentLivenessOptions", DocumentLivenessOptions);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification>("documentVerification", DocumentVerification);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_faceMatchVerification>("faceMatchVerification", FaceMatchVerification);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs>("matcherConfigs", MatcherConfigs);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_selfieVerification>("selfieVerification", SelfieVerification);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_subjectInfo>("subjectInfo", SubjectInfo);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_subjectInfoList>("subjectInfoList", SubjectInfoList);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
