// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    /// <summary>
    /// Document verification configuration
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionConfiguration_documentVerification : IAdditionalDataHolder, IParsable
    {
        /// <summary>Flag to determine the transaction is only focus on front image only</summary>
        public bool? AcceptFrontImageOnly { get; set; }
        /// <summary>List of allowed Trulioo document IDs for bypass of territory and document type criteria outlined elsewhere in the documentsAccepted array. An empty array (or omitting this field) will result in no additional bypass behaviour for the verification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AcceptList { get; set; }
#nullable restore
#else
        public List<string> AcceptList { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of unacceptable Trulioo document IDs for bypass of territory and document type criteria outlined elsewhere in the documentsAccepted array. An empty array (or omitting this field) will result in no additional bypass behaviour for the verification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DenyList { get; set; }
#nullable restore
#else
        public List<string> DenyList { get; set; }
#endif
        /// <summary>List of permissible document types combined with document issuing countries and states or provinces. An empty array will result in accepting all countries and all document types for the verification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted>? DocumentsAccepted { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted> DocumentsAccepted { get; set; }
#endif
        /// <summary>Enables/disables document verification</summary>
        public bool? Enabled { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification"/> and sets the default values.
        /// </summary>
        public TransactionConfiguration_documentVerification()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acceptFrontImageOnly", n => { AcceptFrontImageOnly = n.GetBoolValue(); } },
                { "acceptList", n => { AcceptList = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "denyList", n => { DenyList = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "documentsAccepted", n => { DocumentsAccepted = n.GetCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted>(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted.CreateFromDiscriminatorValue)?.AsList(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("acceptFrontImageOnly", AcceptFrontImageOnly);
            writer.WriteCollectionOfPrimitiveValues<string>("acceptList", AcceptList);
            writer.WriteCollectionOfPrimitiveValues<string>("denyList", DenyList);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted>("documentsAccepted", DocumentsAccepted);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
