// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    /// <summary>Country Code (ISO 3166-1 alpha-2 format)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TransactionConfigurationDocumentVerificationDocumentsAcceptedItemDocumentOriginItemCountryCode
    {
        [EnumMember(Value = "AD")]
        #pragma warning disable CS1591
        Ad,
        #pragma warning restore CS1591
        [EnumMember(Value = "AE")]
        #pragma warning disable CS1591
        Ae,
        #pragma warning restore CS1591
        [EnumMember(Value = "AF")]
        #pragma warning disable CS1591
        Af,
        #pragma warning restore CS1591
        [EnumMember(Value = "AG")]
        #pragma warning disable CS1591
        Ag,
        #pragma warning restore CS1591
        [EnumMember(Value = "AI")]
        #pragma warning disable CS1591
        Ai,
        #pragma warning restore CS1591
        [EnumMember(Value = "AL")]
        #pragma warning disable CS1591
        Al,
        #pragma warning restore CS1591
        [EnumMember(Value = "AM")]
        #pragma warning disable CS1591
        Am,
        #pragma warning restore CS1591
        [EnumMember(Value = "AO")]
        #pragma warning disable CS1591
        Ao,
        #pragma warning restore CS1591
        [EnumMember(Value = "AR")]
        #pragma warning disable CS1591
        Ar,
        #pragma warning restore CS1591
        [EnumMember(Value = "AS")]
        #pragma warning disable CS1591
        AsValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "AT")]
        #pragma warning disable CS1591
        At,
        #pragma warning restore CS1591
        [EnumMember(Value = "AU")]
        #pragma warning disable CS1591
        Au,
        #pragma warning restore CS1591
        [EnumMember(Value = "AW")]
        #pragma warning disable CS1591
        Aw,
        #pragma warning restore CS1591
        [EnumMember(Value = "AX")]
        #pragma warning disable CS1591
        Ax,
        #pragma warning restore CS1591
        [EnumMember(Value = "AZ")]
        #pragma warning disable CS1591
        Az,
        #pragma warning restore CS1591
        [EnumMember(Value = "BA")]
        #pragma warning disable CS1591
        Ba,
        #pragma warning restore CS1591
        [EnumMember(Value = "BB")]
        #pragma warning disable CS1591
        Bb,
        #pragma warning restore CS1591
        [EnumMember(Value = "BD")]
        #pragma warning disable CS1591
        Bd,
        #pragma warning restore CS1591
        [EnumMember(Value = "BE")]
        #pragma warning disable CS1591
        Be,
        #pragma warning restore CS1591
        [EnumMember(Value = "BF")]
        #pragma warning disable CS1591
        Bf,
        #pragma warning restore CS1591
        [EnumMember(Value = "BG")]
        #pragma warning disable CS1591
        Bg,
        #pragma warning restore CS1591
        [EnumMember(Value = "BH")]
        #pragma warning disable CS1591
        Bh,
        #pragma warning restore CS1591
        [EnumMember(Value = "BI")]
        #pragma warning disable CS1591
        Bi,
        #pragma warning restore CS1591
        [EnumMember(Value = "BJ")]
        #pragma warning disable CS1591
        Bj,
        #pragma warning restore CS1591
        [EnumMember(Value = "BL")]
        #pragma warning disable CS1591
        Bl,
        #pragma warning restore CS1591
        [EnumMember(Value = "BM")]
        #pragma warning disable CS1591
        Bm,
        #pragma warning restore CS1591
        [EnumMember(Value = "BN")]
        #pragma warning disable CS1591
        Bn,
        #pragma warning restore CS1591
        [EnumMember(Value = "BO")]
        #pragma warning disable CS1591
        Bo,
        #pragma warning restore CS1591
        [EnumMember(Value = "BQ")]
        #pragma warning disable CS1591
        Bq,
        #pragma warning restore CS1591
        [EnumMember(Value = "BR")]
        #pragma warning disable CS1591
        Br,
        #pragma warning restore CS1591
        [EnumMember(Value = "BS")]
        #pragma warning disable CS1591
        Bs,
        #pragma warning restore CS1591
        [EnumMember(Value = "BT")]
        #pragma warning disable CS1591
        Bt,
        #pragma warning restore CS1591
        [EnumMember(Value = "BV")]
        #pragma warning disable CS1591
        Bv,
        #pragma warning restore CS1591
        [EnumMember(Value = "BW")]
        #pragma warning disable CS1591
        Bw,
        #pragma warning restore CS1591
        [EnumMember(Value = "BY")]
        #pragma warning disable CS1591
        By,
        #pragma warning restore CS1591
        [EnumMember(Value = "BZ")]
        #pragma warning disable CS1591
        Bz,
        #pragma warning restore CS1591
        [EnumMember(Value = "CA")]
        #pragma warning disable CS1591
        Ca,
        #pragma warning restore CS1591
        [EnumMember(Value = "CC")]
        #pragma warning disable CS1591
        Cc,
        #pragma warning restore CS1591
        [EnumMember(Value = "CD")]
        #pragma warning disable CS1591
        Cd,
        #pragma warning restore CS1591
        [EnumMember(Value = "CF")]
        #pragma warning disable CS1591
        Cf,
        #pragma warning restore CS1591
        [EnumMember(Value = "CG")]
        #pragma warning disable CS1591
        Cg,
        #pragma warning restore CS1591
        [EnumMember(Value = "CH")]
        #pragma warning disable CS1591
        Ch,
        #pragma warning restore CS1591
        [EnumMember(Value = "CI")]
        #pragma warning disable CS1591
        Ci,
        #pragma warning restore CS1591
        [EnumMember(Value = "CK")]
        #pragma warning disable CS1591
        Ck,
        #pragma warning restore CS1591
        [EnumMember(Value = "CL")]
        #pragma warning disable CS1591
        Cl,
        #pragma warning restore CS1591
        [EnumMember(Value = "CM")]
        #pragma warning disable CS1591
        Cm,
        #pragma warning restore CS1591
        [EnumMember(Value = "CN")]
        #pragma warning disable CS1591
        Cn,
        #pragma warning restore CS1591
        [EnumMember(Value = "CO")]
        #pragma warning disable CS1591
        Co,
        #pragma warning restore CS1591
        [EnumMember(Value = "CR")]
        #pragma warning disable CS1591
        Cr,
        #pragma warning restore CS1591
        [EnumMember(Value = "CU")]
        #pragma warning disable CS1591
        Cu,
        #pragma warning restore CS1591
        [EnumMember(Value = "CV")]
        #pragma warning disable CS1591
        Cv,
        #pragma warning restore CS1591
        [EnumMember(Value = "CW")]
        #pragma warning disable CS1591
        Cw,
        #pragma warning restore CS1591
        [EnumMember(Value = "CX")]
        #pragma warning disable CS1591
        Cx,
        #pragma warning restore CS1591
        [EnumMember(Value = "CY")]
        #pragma warning disable CS1591
        Cy,
        #pragma warning restore CS1591
        [EnumMember(Value = "CZ")]
        #pragma warning disable CS1591
        Cz,
        #pragma warning restore CS1591
        [EnumMember(Value = "DE")]
        #pragma warning disable CS1591
        De,
        #pragma warning restore CS1591
        [EnumMember(Value = "DJ")]
        #pragma warning disable CS1591
        Dj,
        #pragma warning restore CS1591
        [EnumMember(Value = "DK")]
        #pragma warning disable CS1591
        Dk,
        #pragma warning restore CS1591
        [EnumMember(Value = "DM")]
        #pragma warning disable CS1591
        Dm,
        #pragma warning restore CS1591
        [EnumMember(Value = "DO")]
        #pragma warning disable CS1591
        DoValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "DZ")]
        #pragma warning disable CS1591
        Dz,
        #pragma warning restore CS1591
        [EnumMember(Value = "EC")]
        #pragma warning disable CS1591
        Ec,
        #pragma warning restore CS1591
        [EnumMember(Value = "EE")]
        #pragma warning disable CS1591
        Ee,
        #pragma warning restore CS1591
        [EnumMember(Value = "EG")]
        #pragma warning disable CS1591
        Eg,
        #pragma warning restore CS1591
        [EnumMember(Value = "EH")]
        #pragma warning disable CS1591
        Eh,
        #pragma warning restore CS1591
        [EnumMember(Value = "ER")]
        #pragma warning disable CS1591
        Er,
        #pragma warning restore CS1591
        [EnumMember(Value = "ES")]
        #pragma warning disable CS1591
        Es,
        #pragma warning restore CS1591
        [EnumMember(Value = "ET")]
        #pragma warning disable CS1591
        Et,
        #pragma warning restore CS1591
        [EnumMember(Value = "FI")]
        #pragma warning disable CS1591
        Fi,
        #pragma warning restore CS1591
        [EnumMember(Value = "FJ")]
        #pragma warning disable CS1591
        Fj,
        #pragma warning restore CS1591
        [EnumMember(Value = "FK")]
        #pragma warning disable CS1591
        Fk,
        #pragma warning restore CS1591
        [EnumMember(Value = "FM")]
        #pragma warning disable CS1591
        Fm,
        #pragma warning restore CS1591
        [EnumMember(Value = "FO")]
        #pragma warning disable CS1591
        Fo,
        #pragma warning restore CS1591
        [EnumMember(Value = "FR")]
        #pragma warning disable CS1591
        Fr,
        #pragma warning restore CS1591
        [EnumMember(Value = "GA")]
        #pragma warning disable CS1591
        Ga,
        #pragma warning restore CS1591
        [EnumMember(Value = "GB")]
        #pragma warning disable CS1591
        Gb,
        #pragma warning restore CS1591
        [EnumMember(Value = "GD")]
        #pragma warning disable CS1591
        Gd,
        #pragma warning restore CS1591
        [EnumMember(Value = "GE")]
        #pragma warning disable CS1591
        Ge,
        #pragma warning restore CS1591
        [EnumMember(Value = "GF")]
        #pragma warning disable CS1591
        Gf,
        #pragma warning restore CS1591
        [EnumMember(Value = "GG")]
        #pragma warning disable CS1591
        Gg,
        #pragma warning restore CS1591
        [EnumMember(Value = "GH")]
        #pragma warning disable CS1591
        Gh,
        #pragma warning restore CS1591
        [EnumMember(Value = "GI")]
        #pragma warning disable CS1591
        Gi,
        #pragma warning restore CS1591
        [EnumMember(Value = "GL")]
        #pragma warning disable CS1591
        Gl,
        #pragma warning restore CS1591
        [EnumMember(Value = "GM")]
        #pragma warning disable CS1591
        Gm,
        #pragma warning restore CS1591
        [EnumMember(Value = "GN")]
        #pragma warning disable CS1591
        Gn,
        #pragma warning restore CS1591
        [EnumMember(Value = "GP")]
        #pragma warning disable CS1591
        Gp,
        #pragma warning restore CS1591
        [EnumMember(Value = "GQ")]
        #pragma warning disable CS1591
        Gq,
        #pragma warning restore CS1591
        [EnumMember(Value = "GR")]
        #pragma warning disable CS1591
        Gr,
        #pragma warning restore CS1591
        [EnumMember(Value = "GS")]
        #pragma warning disable CS1591
        Gs,
        #pragma warning restore CS1591
        [EnumMember(Value = "GT")]
        #pragma warning disable CS1591
        Gt,
        #pragma warning restore CS1591
        [EnumMember(Value = "GU")]
        #pragma warning disable CS1591
        Gu,
        #pragma warning restore CS1591
        [EnumMember(Value = "GW")]
        #pragma warning disable CS1591
        Gw,
        #pragma warning restore CS1591
        [EnumMember(Value = "GY")]
        #pragma warning disable CS1591
        Gy,
        #pragma warning restore CS1591
        [EnumMember(Value = "HK")]
        #pragma warning disable CS1591
        Hk,
        #pragma warning restore CS1591
        [EnumMember(Value = "HM")]
        #pragma warning disable CS1591
        Hm,
        #pragma warning restore CS1591
        [EnumMember(Value = "HN")]
        #pragma warning disable CS1591
        Hn,
        #pragma warning restore CS1591
        [EnumMember(Value = "HR")]
        #pragma warning disable CS1591
        Hr,
        #pragma warning restore CS1591
        [EnumMember(Value = "HT")]
        #pragma warning disable CS1591
        Ht,
        #pragma warning restore CS1591
        [EnumMember(Value = "HU")]
        #pragma warning disable CS1591
        Hu,
        #pragma warning restore CS1591
        [EnumMember(Value = "ID")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
        [EnumMember(Value = "IE")]
        #pragma warning disable CS1591
        Ie,
        #pragma warning restore CS1591
        [EnumMember(Value = "IL")]
        #pragma warning disable CS1591
        Il,
        #pragma warning restore CS1591
        [EnumMember(Value = "IM")]
        #pragma warning disable CS1591
        Im,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN")]
        #pragma warning disable CS1591
        InValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "IO")]
        #pragma warning disable CS1591
        Io,
        #pragma warning restore CS1591
        [EnumMember(Value = "IQ")]
        #pragma warning disable CS1591
        Iq,
        #pragma warning restore CS1591
        [EnumMember(Value = "IR")]
        #pragma warning disable CS1591
        Ir,
        #pragma warning restore CS1591
        [EnumMember(Value = "IS")]
        #pragma warning disable CS1591
        IsValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "IT")]
        #pragma warning disable CS1591
        It,
        #pragma warning restore CS1591
        [EnumMember(Value = "JE")]
        #pragma warning disable CS1591
        Je,
        #pragma warning restore CS1591
        [EnumMember(Value = "JM")]
        #pragma warning disable CS1591
        Jm,
        #pragma warning restore CS1591
        [EnumMember(Value = "JO")]
        #pragma warning disable CS1591
        Jo,
        #pragma warning restore CS1591
        [EnumMember(Value = "JP")]
        #pragma warning disable CS1591
        Jp,
        #pragma warning restore CS1591
        [EnumMember(Value = "KE")]
        #pragma warning disable CS1591
        Ke,
        #pragma warning restore CS1591
        [EnumMember(Value = "KG")]
        #pragma warning disable CS1591
        Kg,
        #pragma warning restore CS1591
        [EnumMember(Value = "KH")]
        #pragma warning disable CS1591
        Kh,
        #pragma warning restore CS1591
        [EnumMember(Value = "KI")]
        #pragma warning disable CS1591
        Ki,
        #pragma warning restore CS1591
        [EnumMember(Value = "KM")]
        #pragma warning disable CS1591
        Km,
        #pragma warning restore CS1591
        [EnumMember(Value = "KN")]
        #pragma warning disable CS1591
        Kn,
        #pragma warning restore CS1591
        [EnumMember(Value = "KP")]
        #pragma warning disable CS1591
        Kp,
        #pragma warning restore CS1591
        [EnumMember(Value = "KR")]
        #pragma warning disable CS1591
        Kr,
        #pragma warning restore CS1591
        [EnumMember(Value = "KW")]
        #pragma warning disable CS1591
        Kw,
        #pragma warning restore CS1591
        [EnumMember(Value = "KY")]
        #pragma warning disable CS1591
        Ky,
        #pragma warning restore CS1591
        [EnumMember(Value = "KZ")]
        #pragma warning disable CS1591
        Kz,
        #pragma warning restore CS1591
        [EnumMember(Value = "LA")]
        #pragma warning disable CS1591
        La,
        #pragma warning restore CS1591
        [EnumMember(Value = "LB")]
        #pragma warning disable CS1591
        Lb,
        #pragma warning restore CS1591
        [EnumMember(Value = "LC")]
        #pragma warning disable CS1591
        Lc,
        #pragma warning restore CS1591
        [EnumMember(Value = "LI")]
        #pragma warning disable CS1591
        Li,
        #pragma warning restore CS1591
        [EnumMember(Value = "LK")]
        #pragma warning disable CS1591
        Lk,
        #pragma warning restore CS1591
        [EnumMember(Value = "LR")]
        #pragma warning disable CS1591
        Lr,
        #pragma warning restore CS1591
        [EnumMember(Value = "LS")]
        #pragma warning disable CS1591
        Ls,
        #pragma warning restore CS1591
        [EnumMember(Value = "LT")]
        #pragma warning disable CS1591
        Lt,
        #pragma warning restore CS1591
        [EnumMember(Value = "LU")]
        #pragma warning disable CS1591
        Lu,
        #pragma warning restore CS1591
        [EnumMember(Value = "LV")]
        #pragma warning disable CS1591
        Lv,
        #pragma warning restore CS1591
        [EnumMember(Value = "LY")]
        #pragma warning disable CS1591
        Ly,
        #pragma warning restore CS1591
        [EnumMember(Value = "MA")]
        #pragma warning disable CS1591
        Ma,
        #pragma warning restore CS1591
        [EnumMember(Value = "MC")]
        #pragma warning disable CS1591
        Mc,
        #pragma warning restore CS1591
        [EnumMember(Value = "MD")]
        #pragma warning disable CS1591
        Md,
        #pragma warning restore CS1591
        [EnumMember(Value = "ME")]
        #pragma warning disable CS1591
        Me,
        #pragma warning restore CS1591
        [EnumMember(Value = "MF")]
        #pragma warning disable CS1591
        Mf,
        #pragma warning restore CS1591
        [EnumMember(Value = "MG")]
        #pragma warning disable CS1591
        Mg,
        #pragma warning restore CS1591
        [EnumMember(Value = "MH")]
        #pragma warning disable CS1591
        Mh,
        #pragma warning restore CS1591
        [EnumMember(Value = "MK")]
        #pragma warning disable CS1591
        Mk,
        #pragma warning restore CS1591
        [EnumMember(Value = "ML")]
        #pragma warning disable CS1591
        Ml,
        #pragma warning restore CS1591
        [EnumMember(Value = "MM")]
        #pragma warning disable CS1591
        Mm,
        #pragma warning restore CS1591
        [EnumMember(Value = "MN")]
        #pragma warning disable CS1591
        Mn,
        #pragma warning restore CS1591
        [EnumMember(Value = "MO")]
        #pragma warning disable CS1591
        Mo,
        #pragma warning restore CS1591
        [EnumMember(Value = "MP")]
        #pragma warning disable CS1591
        Mp,
        #pragma warning restore CS1591
        [EnumMember(Value = "MQ")]
        #pragma warning disable CS1591
        Mq,
        #pragma warning restore CS1591
        [EnumMember(Value = "MR")]
        #pragma warning disable CS1591
        Mr,
        #pragma warning restore CS1591
        [EnumMember(Value = "MS")]
        #pragma warning disable CS1591
        Ms,
        #pragma warning restore CS1591
        [EnumMember(Value = "MT")]
        #pragma warning disable CS1591
        Mt,
        #pragma warning restore CS1591
        [EnumMember(Value = "MU")]
        #pragma warning disable CS1591
        Mu,
        #pragma warning restore CS1591
        [EnumMember(Value = "MV")]
        #pragma warning disable CS1591
        Mv,
        #pragma warning restore CS1591
        [EnumMember(Value = "MW")]
        #pragma warning disable CS1591
        Mw,
        #pragma warning restore CS1591
        [EnumMember(Value = "MX")]
        #pragma warning disable CS1591
        Mx,
        #pragma warning restore CS1591
        [EnumMember(Value = "MY")]
        #pragma warning disable CS1591
        My,
        #pragma warning restore CS1591
        [EnumMember(Value = "MZ")]
        #pragma warning disable CS1591
        Mz,
        #pragma warning restore CS1591
        [EnumMember(Value = "NA")]
        #pragma warning disable CS1591
        Na,
        #pragma warning restore CS1591
        [EnumMember(Value = "NC")]
        #pragma warning disable CS1591
        Nc,
        #pragma warning restore CS1591
        [EnumMember(Value = "NE")]
        #pragma warning disable CS1591
        Ne,
        #pragma warning restore CS1591
        [EnumMember(Value = "NF")]
        #pragma warning disable CS1591
        Nf,
        #pragma warning restore CS1591
        [EnumMember(Value = "NG")]
        #pragma warning disable CS1591
        Ng,
        #pragma warning restore CS1591
        [EnumMember(Value = "NI")]
        #pragma warning disable CS1591
        Ni,
        #pragma warning restore CS1591
        [EnumMember(Value = "NL")]
        #pragma warning disable CS1591
        Nl,
        #pragma warning restore CS1591
        [EnumMember(Value = "NO")]
        #pragma warning disable CS1591
        No,
        #pragma warning restore CS1591
        [EnumMember(Value = "NP")]
        #pragma warning disable CS1591
        Np,
        #pragma warning restore CS1591
        [EnumMember(Value = "NR")]
        #pragma warning disable CS1591
        Nr,
        #pragma warning restore CS1591
        [EnumMember(Value = "NU")]
        #pragma warning disable CS1591
        Nu,
        #pragma warning restore CS1591
        [EnumMember(Value = "NZ")]
        #pragma warning disable CS1591
        Nz,
        #pragma warning restore CS1591
        [EnumMember(Value = "OM")]
        #pragma warning disable CS1591
        Om,
        #pragma warning restore CS1591
        [EnumMember(Value = "PA")]
        #pragma warning disable CS1591
        Pa,
        #pragma warning restore CS1591
        [EnumMember(Value = "PE")]
        #pragma warning disable CS1591
        Pe,
        #pragma warning restore CS1591
        [EnumMember(Value = "PF")]
        #pragma warning disable CS1591
        Pf,
        #pragma warning restore CS1591
        [EnumMember(Value = "PG")]
        #pragma warning disable CS1591
        Pg,
        #pragma warning restore CS1591
        [EnumMember(Value = "PH")]
        #pragma warning disable CS1591
        Ph,
        #pragma warning restore CS1591
        [EnumMember(Value = "PK")]
        #pragma warning disable CS1591
        Pk,
        #pragma warning restore CS1591
        [EnumMember(Value = "PL")]
        #pragma warning disable CS1591
        Pl,
        #pragma warning restore CS1591
        [EnumMember(Value = "PM")]
        #pragma warning disable CS1591
        Pm,
        #pragma warning restore CS1591
        [EnumMember(Value = "PN")]
        #pragma warning disable CS1591
        Pn,
        #pragma warning restore CS1591
        [EnumMember(Value = "PR")]
        #pragma warning disable CS1591
        Pr,
        #pragma warning restore CS1591
        [EnumMember(Value = "PS")]
        #pragma warning disable CS1591
        Ps,
        #pragma warning restore CS1591
        [EnumMember(Value = "PT")]
        #pragma warning disable CS1591
        Pt,
        #pragma warning restore CS1591
        [EnumMember(Value = "PW")]
        #pragma warning disable CS1591
        Pw,
        #pragma warning restore CS1591
        [EnumMember(Value = "PY")]
        #pragma warning disable CS1591
        Py,
        #pragma warning restore CS1591
        [EnumMember(Value = "QA")]
        #pragma warning disable CS1591
        Qa,
        #pragma warning restore CS1591
        [EnumMember(Value = "RE")]
        #pragma warning disable CS1591
        Re,
        #pragma warning restore CS1591
        [EnumMember(Value = "RO")]
        #pragma warning disable CS1591
        Ro,
        #pragma warning restore CS1591
        [EnumMember(Value = "RS")]
        #pragma warning disable CS1591
        Rs,
        #pragma warning restore CS1591
        [EnumMember(Value = "RU")]
        #pragma warning disable CS1591
        Ru,
        #pragma warning restore CS1591
        [EnumMember(Value = "RW")]
        #pragma warning disable CS1591
        Rw,
        #pragma warning restore CS1591
        [EnumMember(Value = "SA")]
        #pragma warning disable CS1591
        Sa,
        #pragma warning restore CS1591
        [EnumMember(Value = "SB")]
        #pragma warning disable CS1591
        Sb,
        #pragma warning restore CS1591
        [EnumMember(Value = "SC")]
        #pragma warning disable CS1591
        Sc,
        #pragma warning restore CS1591
        [EnumMember(Value = "SD")]
        #pragma warning disable CS1591
        Sd,
        #pragma warning restore CS1591
        [EnumMember(Value = "SE")]
        #pragma warning disable CS1591
        Se,
        #pragma warning restore CS1591
        [EnumMember(Value = "SG")]
        #pragma warning disable CS1591
        Sg,
        #pragma warning restore CS1591
        [EnumMember(Value = "SH")]
        #pragma warning disable CS1591
        Sh,
        #pragma warning restore CS1591
        [EnumMember(Value = "SI")]
        #pragma warning disable CS1591
        Si,
        #pragma warning restore CS1591
        [EnumMember(Value = "SJ")]
        #pragma warning disable CS1591
        Sj,
        #pragma warning restore CS1591
        [EnumMember(Value = "SK")]
        #pragma warning disable CS1591
        Sk,
        #pragma warning restore CS1591
        [EnumMember(Value = "SL")]
        #pragma warning disable CS1591
        Sl,
        #pragma warning restore CS1591
        [EnumMember(Value = "SM")]
        #pragma warning disable CS1591
        Sm,
        #pragma warning restore CS1591
        [EnumMember(Value = "SN")]
        #pragma warning disable CS1591
        Sn,
        #pragma warning restore CS1591
        [EnumMember(Value = "SO")]
        #pragma warning disable CS1591
        So,
        #pragma warning restore CS1591
        [EnumMember(Value = "SR")]
        #pragma warning disable CS1591
        Sr,
        #pragma warning restore CS1591
        [EnumMember(Value = "SS")]
        #pragma warning disable CS1591
        Ss,
        #pragma warning restore CS1591
        [EnumMember(Value = "ST")]
        #pragma warning disable CS1591
        St,
        #pragma warning restore CS1591
        [EnumMember(Value = "SV")]
        #pragma warning disable CS1591
        Sv,
        #pragma warning restore CS1591
        [EnumMember(Value = "SX")]
        #pragma warning disable CS1591
        Sx,
        #pragma warning restore CS1591
        [EnumMember(Value = "SY")]
        #pragma warning disable CS1591
        Sy,
        #pragma warning restore CS1591
        [EnumMember(Value = "SZ")]
        #pragma warning disable CS1591
        Sz,
        #pragma warning restore CS1591
        [EnumMember(Value = "TC")]
        #pragma warning disable CS1591
        Tc,
        #pragma warning restore CS1591
        [EnumMember(Value = "TD")]
        #pragma warning disable CS1591
        Td,
        #pragma warning restore CS1591
        [EnumMember(Value = "TF")]
        #pragma warning disable CS1591
        Tf,
        #pragma warning restore CS1591
        [EnumMember(Value = "TG")]
        #pragma warning disable CS1591
        Tg,
        #pragma warning restore CS1591
        [EnumMember(Value = "TH")]
        #pragma warning disable CS1591
        Th,
        #pragma warning restore CS1591
        [EnumMember(Value = "TJ")]
        #pragma warning disable CS1591
        Tj,
        #pragma warning restore CS1591
        [EnumMember(Value = "TK")]
        #pragma warning disable CS1591
        Tk,
        #pragma warning restore CS1591
        [EnumMember(Value = "TL")]
        #pragma warning disable CS1591
        Tl,
        #pragma warning restore CS1591
        [EnumMember(Value = "TM")]
        #pragma warning disable CS1591
        Tm,
        #pragma warning restore CS1591
        [EnumMember(Value = "TN")]
        #pragma warning disable CS1591
        Tn,
        #pragma warning restore CS1591
        [EnumMember(Value = "TO")]
        #pragma warning disable CS1591
        To,
        #pragma warning restore CS1591
        [EnumMember(Value = "TR")]
        #pragma warning disable CS1591
        Tr,
        #pragma warning restore CS1591
        [EnumMember(Value = "TT")]
        #pragma warning disable CS1591
        Tt,
        #pragma warning restore CS1591
        [EnumMember(Value = "TV")]
        #pragma warning disable CS1591
        Tv,
        #pragma warning restore CS1591
        [EnumMember(Value = "TW")]
        #pragma warning disable CS1591
        Tw,
        #pragma warning restore CS1591
        [EnumMember(Value = "TZ")]
        #pragma warning disable CS1591
        Tz,
        #pragma warning restore CS1591
        [EnumMember(Value = "UA")]
        #pragma warning disable CS1591
        Ua,
        #pragma warning restore CS1591
        [EnumMember(Value = "UG")]
        #pragma warning disable CS1591
        Ug,
        #pragma warning restore CS1591
        [EnumMember(Value = "UM")]
        #pragma warning disable CS1591
        Um,
        #pragma warning restore CS1591
        [EnumMember(Value = "US")]
        #pragma warning disable CS1591
        Us,
        #pragma warning restore CS1591
        [EnumMember(Value = "UY")]
        #pragma warning disable CS1591
        Uy,
        #pragma warning restore CS1591
        [EnumMember(Value = "UZ")]
        #pragma warning disable CS1591
        Uz,
        #pragma warning restore CS1591
        [EnumMember(Value = "VA")]
        #pragma warning disable CS1591
        Va,
        #pragma warning restore CS1591
        [EnumMember(Value = "VC")]
        #pragma warning disable CS1591
        Vc,
        #pragma warning restore CS1591
        [EnumMember(Value = "VE")]
        #pragma warning disable CS1591
        Ve,
        #pragma warning restore CS1591
        [EnumMember(Value = "VG")]
        #pragma warning disable CS1591
        Vg,
        #pragma warning restore CS1591
        [EnumMember(Value = "VI")]
        #pragma warning disable CS1591
        Vi,
        #pragma warning restore CS1591
        [EnumMember(Value = "VN")]
        #pragma warning disable CS1591
        Vn,
        #pragma warning restore CS1591
        [EnumMember(Value = "VU")]
        #pragma warning disable CS1591
        Vu,
        #pragma warning restore CS1591
        [EnumMember(Value = "WF")]
        #pragma warning disable CS1591
        Wf,
        #pragma warning restore CS1591
        [EnumMember(Value = "WS")]
        #pragma warning disable CS1591
        Ws,
        #pragma warning restore CS1591
        [EnumMember(Value = "XK")]
        #pragma warning disable CS1591
        Xk,
        #pragma warning restore CS1591
        [EnumMember(Value = "YE")]
        #pragma warning disable CS1591
        Ye,
        #pragma warning restore CS1591
        [EnumMember(Value = "YT")]
        #pragma warning disable CS1591
        Yt,
        #pragma warning restore CS1591
        [EnumMember(Value = "ZA")]
        #pragma warning disable CS1591
        Za,
        #pragma warning restore CS1591
        [EnumMember(Value = "ZM")]
        #pragma warning disable CS1591
        Zm,
        #pragma warning restore CS1591
        [EnumMember(Value = "ZW")]
        #pragma warning disable CS1591
        Zw,
        #pragma warning restore CS1591
    }
}
