// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransactionConfiguration_documentVerification_documentsAccepted : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>List of permissible issuing countries combined with states or provinces per specified document type. An empty array will result in accepting all countries.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin>? DocumentOrigin { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin> DocumentOrigin { get; set; }
#endif
        /// <summary>Document type.</summary>
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentType? DocumentType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted"/> and sets the default values.
        /// </summary>
        public TransactionConfiguration_documentVerification_documentsAccepted()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "documentOrigin", n => { DocumentOrigin = n.GetCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin>(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin.CreateFromDiscriminatorValue)?.AsList(); } },
                { "documentType", n => { DocumentType = n.GetEnumValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin>("documentOrigin", DocumentOrigin);
            writer.WriteEnumValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentType>("documentType", DocumentType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
