// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TransactionConfigurationMatcherConfigsItemMatchersItemToken
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "FIRST_NAME")]
        #pragma warning disable CS1591
        FirstName,
        #pragma warning restore CS1591
        [EnumMember(Value = "MIDDLE_NAME")]
        #pragma warning disable CS1591
        MiddleName,
        #pragma warning restore CS1591
        [EnumMember(Value = "LAST_NAME")]
        #pragma warning disable CS1591
        LastName,
        #pragma warning restore CS1591
        [EnumMember(Value = "FULL_NAME")]
        #pragma warning disable CS1591
        FullName,
        #pragma warning restore CS1591
        [EnumMember(Value = "DATE_OF_BIRTH")]
        #pragma warning disable CS1591
        DateOfBirth,
        #pragma warning restore CS1591
        [EnumMember(Value = "ADDRESS_LINE_1")]
        #pragma warning disable CS1591
        AddressLine1,
        #pragma warning restore CS1591
        [EnumMember(Value = "CITY")]
        #pragma warning disable CS1591
        City,
        #pragma warning restore CS1591
        [EnumMember(Value = "STATE_PROVINCE")]
        #pragma warning disable CS1591
        StateProvince,
        #pragma warning restore CS1591
        [EnumMember(Value = "POSTAL_CODE")]
        #pragma warning disable CS1591
        PostalCode,
        #pragma warning restore CS1591
        [EnumMember(Value = "COUNTRY")]
        #pragma warning disable CS1591
        Country,
        #pragma warning restore CS1591
        [EnumMember(Value = "FIRST_LAST_NAME")]
        #pragma warning disable CS1591
        FirstLastName,
        #pragma warning restore CS1591
        [EnumMember(Value = "SECOND_LAST_NAME")]
        #pragma warning disable CS1591
        SecondLastName,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPOUSE_LAST_NAME")]
        #pragma warning disable CS1591
        SpouseLastName,
        #pragma warning restore CS1591
        [EnumMember(Value = "BIRTH_LAST_NAME")]
        #pragma warning disable CS1591
        BirthLastName,
        #pragma warning restore CS1591
    }
}
