// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    /// <summary>The decision of the verification.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TransactionResultResponse_status
    {
        [EnumMember(Value = "ACCEPTED")]
        #pragma warning disable CS1591
        ACCEPTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "REVIEW")]
        #pragma warning disable CS1591
        REVIEW,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECLINED")]
        #pragma warning disable CS1591
        DECLINED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        ERROR,
        #pragma warning restore CS1591
        [EnumMember(Value = "NO_RESULT")]
        #pragma warning disable CS1591
        NO_RESULT,
        #pragma warning restore CS1591
    }
}
