// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransactionResultResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique identifier referencing client id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>The document property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.Document? Document { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.Document Document { get; set; }
#endif
        /// <summary>List of errors related to image processing, network with vendor, or vendor errors during verification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Errors { get; set; }
#nullable restore
#else
        public List<string> Errors { get; set; }
#endif
        /// <summary>The object contain all submitted images.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.ImageIds? Images { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.ImageIds Images { get; set; }
#endif
        /// <summary>Reasons of verification failure.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.Indicator>? Indicators { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.Indicator> Indicators { get; set; }
#endif
        /// <summary>List of results from user-input matching in the workflow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.MatcherResult>? MatcherResults { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.MatcherResult> MatcherResults { get; set; }
#endif
        /// <summary>The person property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.Person? Person { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.Person Person { get; set; }
#endif
        /// <summary>The decision of the verification.</summary>
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResultResponse_status? Status { get; set; }
        /// <summary>Date and time (ISO 8601) when the transaction took place.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeOfTransaction { get; set; }
#nullable restore
#else
        public string TimeOfTransaction { get; set; }
#endif
        /// <summary>The unique identifier of a Trulioo document verification transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransactionId { get; set; }
#nullable restore
#else
        public string TransactionId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResultResponse"/> and sets the default values.
        /// </summary>
        public TransactionResultResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResultResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResultResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResultResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "clientId", n => { ClientId = n.GetStringValue(); } },
                { "document", n => { Document = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.Document>(global::Soenneker.Trulioo.OpenApiClient.Models.Document.CreateFromDiscriminatorValue); } },
                { "errors", n => { Errors = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "images", n => { Images = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.ImageIds>(global::Soenneker.Trulioo.OpenApiClient.Models.ImageIds.CreateFromDiscriminatorValue); } },
                { "indicators", n => { Indicators = n.GetCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.Indicator>(global::Soenneker.Trulioo.OpenApiClient.Models.Indicator.CreateFromDiscriminatorValue)?.AsList(); } },
                { "matcherResults", n => { MatcherResults = n.GetCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.MatcherResult>(global::Soenneker.Trulioo.OpenApiClient.Models.MatcherResult.CreateFromDiscriminatorValue)?.AsList(); } },
                { "person", n => { Person = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.Person>(global::Soenneker.Trulioo.OpenApiClient.Models.Person.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResultResponse_status>(); } },
                { "timeOfTransaction", n => { TimeOfTransaction = n.GetStringValue(); } },
                { "transactionId", n => { TransactionId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("clientId", ClientId);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.Document>("document", Document);
            writer.WriteCollectionOfPrimitiveValues<string>("errors", Errors);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.ImageIds>("images", Images);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.Indicator>("indicators", Indicators);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.MatcherResult>("matcherResults", MatcherResults);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.Person>("person", Person);
            writer.WriteEnumValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResultResponse_status>("status", Status);
            writer.WriteStringValue("timeOfTransaction", TimeOfTransaction);
            writer.WriteStringValue("transactionId", TransactionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
