// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    /// <summary>
    /// Document liveness check configuration (NOTE: If set, this config overrides documentLivenessOptions). Supported Calibrations: Screen Used=[MEDIUM, HIGH], Printout=[MEDIUM, HIGH] Portrait Substitution=[MEDIUM, HIGH], Digital Manipulation=[LOW, MEDIUM, HIGH].
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionConfiguration_documentLivenessConfig : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The digitalManipulation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck? DigitalManipulation { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck DigitalManipulation { get; set; }
#endif
        /// <summary>The portraitSubstitution property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck? PortraitSubstitution { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck PortraitSubstitution { get; set; }
#endif
        /// <summary>The printout property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck? Printout { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck Printout { get; set; }
#endif
        /// <summary>The screenUsed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck? ScreenUsed { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck ScreenUsed { get; set; }
#endif
        /// <summary>Skip Cropped Image check</summary>
        public bool? SkipAlreadyCropped { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentLivenessConfig"/> and sets the default values.
        /// </summary>
        public TransactionConfiguration_documentLivenessConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentLivenessConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentLivenessConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentLivenessConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "digitalManipulation", n => { DigitalManipulation = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck>(global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck.CreateFromDiscriminatorValue); } },
                { "portraitSubstitution", n => { PortraitSubstitution = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck>(global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck.CreateFromDiscriminatorValue); } },
                { "printout", n => { Printout = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck>(global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck.CreateFromDiscriminatorValue); } },
                { "screenUsed", n => { ScreenUsed = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck>(global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck.CreateFromDiscriminatorValue); } },
                { "skipAlreadyCropped", n => { SkipAlreadyCropped = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck>("digitalManipulation", DigitalManipulation);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck>("portraitSubstitution", PortraitSubstitution);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck>("printout", Printout);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.LivenessCheck>("screenUsed", ScreenUsed);
            writer.WriteBoolValue("skipAlreadyCropped", SkipAlreadyCropped);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
