// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Country Code (ISO 3166-1 alpha-2 format)</summary>
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin_countryCode? CountryCode { get; set; }
        /// <summary>List of allowed states or provinces corresponding to a specified document type and its issuing country. This configuration applies exclusively to the United States and Canada and is applicable only to specific document types. To set the document type configuration solely at the country level, input an empty array as the jurisdiction value. When all jurisdictions are listed, the document must contain jurisdictional information.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin_jurisdictions>? Jurisdictions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin_jurisdictions> Jurisdictions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin"/> and sets the default values.
        /// </summary>
        public TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "countryCode", n => { CountryCode = n.GetEnumValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin_countryCode>(); } },
                { "jurisdictions", n => { Jurisdictions = n.GetCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin_jurisdictions>(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin_jurisdictions.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin_countryCode>("countryCode", CountryCode);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_documentVerification_documentsAccepted_documentOrigin_jurisdictions>("jurisdictions", Jurisdictions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
