// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Models
{
    /// <summary>
    /// This configuration object will control matcher strategies in the matcher pipeline. The configuration object will control transliteration, tokenization, and basic fuzzy match. Before running match pipeline, both inputs will be normalized with diacritic removal.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionConfiguration_matcherConfigs_matchers_strategy : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The basicFuzzyMatch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_basicFuzzyMatch? BasicFuzzyMatch { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_basicFuzzyMatch BasicFuzzyMatch { get; set; }
#endif
        /// <summary>The tokenMatch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_tokenMatch? TokenMatch { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_tokenMatch TokenMatch { get; set; }
#endif
        /// <summary>The transliterationMatch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_transliterationMatch? TransliterationMatch { get; set; }
#nullable restore
#else
        public global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_transliterationMatch TransliterationMatch { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy"/> and sets the default values.
        /// </summary>
        public TransactionConfiguration_matcherConfigs_matchers_strategy()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "basicFuzzyMatch", n => { BasicFuzzyMatch = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_basicFuzzyMatch>(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_basicFuzzyMatch.CreateFromDiscriminatorValue); } },
                { "tokenMatch", n => { TokenMatch = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_tokenMatch>(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_tokenMatch.CreateFromDiscriminatorValue); } },
                { "transliterationMatch", n => { TransliterationMatch = n.GetObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_transliterationMatch>(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_transliterationMatch.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_basicFuzzyMatch>("basicFuzzyMatch", BasicFuzzyMatch);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_tokenMatch>("tokenMatch", TokenMatch);
            writer.WriteObjectValue<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration_matcherConfigs_matchers_strategy_transliterationMatch>("transliterationMatch", TransliterationMatch);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
