// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Documents;
using Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Item;
using Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Verify;
using Soenneker.Trulioo.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Customer.Transactions
{
    /// <summary>
    /// Builds and executes requests for operations under \customer\transactions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The documents property</summary>
        public global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Documents.DocumentsRequestBuilder Documents
        {
            get => new global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Documents.DocumentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The verify property</summary>
        public global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Verify.VerifyRequestBuilder Verify
        {
            get => new global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Verify.VerifyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Trulioo.OpenApiClient.customer.transactions.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Item.WithTransactionItemRequestBuilder"/></returns>
        public global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Item.WithTransactionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("transactionId", position);
                return new global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Item.WithTransactionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.TransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer/transactions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.TransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer/transactions", rawUrl)
        {
        }
        /// <summary>
        /// Creates a transaction with configuration options for document and/or selfie liveness verification.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResponse400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResponse500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResponse?> PostAsync(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResponse> PostAsync(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResponse400Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResponse500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResponse>(requestInfo, global::Soenneker.Trulioo.OpenApiClient.Models.TransactionResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a transaction with configuration options for document and/or selfie liveness verification.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Trulioo.OpenApiClient.Models.TransactionConfiguration body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.TransactionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.TransactionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.TransactionsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
