// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Item.Images.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Item.Images
{
    /// <summary>
    /// Builds and executes requests for operations under \customer\transactions\{transactionId}\images
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImagesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Trulioo.OpenApiClient.customer.transactions.item.images.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Item.Images.Item.WithImageItemRequestBuilder"/></returns>
        public global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Item.Images.Item.WithImageItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("imageId", position);
                return new global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Item.Images.Item.WithImageItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Item.Images.ImagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImagesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer/transactions/{transactionId}/images", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Item.Images.ImagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ImagesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer/transactions/{transactionId}/images", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
