// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Customer.Transactions.Documents
{
    /// <summary>The `front` or `back` of the document, or `live` for selfie. Use `pdf` for PDF files.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DocumentsPostRequestBody
    {
        [EnumMember(Value = "front")]
        #pragma warning disable CS1591
        Front,
        #pragma warning restore CS1591
        [EnumMember(Value = "back")]
        #pragma warning disable CS1591
        Back,
        #pragma warning restore CS1591
        [EnumMember(Value = "live")]
        #pragma warning disable CS1591
        Live,
        #pragma warning restore CS1591
        [EnumMember(Value = "pdf")]
        #pragma warning disable CS1591
        Pdf,
        #pragma warning restore CS1591
    }
}
