// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Trulioo.OpenApiClient.Customer.Handoff;
using Soenneker.Trulioo.OpenApiClient.Customer.Transactions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Trulioo.OpenApiClient.Customer
{
    /// <summary>
    /// Builds and executes requests for operations under \customer
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The handoff property</summary>
        public global::Soenneker.Trulioo.OpenApiClient.Customer.Handoff.HandoffRequestBuilder Handoff
        {
            get => new global::Soenneker.Trulioo.OpenApiClient.Customer.Handoff.HandoffRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactions property</summary>
        public global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.TransactionsRequestBuilder Transactions
        {
            get => new global::Soenneker.Trulioo.OpenApiClient.Customer.Transactions.TransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Customer.CustomerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Trulioo.OpenApiClient.Customer.CustomerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CustomerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/customer", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
